### ISSUE TITLE
Proyecto final

### ISSUE THREAD

**Issue by Blanca-estela-valerio-rivero** [SistemasTecTlaxiaco/actividad-final-proyecto-final-confident-students#1]
[REALIZAR UN APP QUE CONTENGA OPERACIONES      DE INSERCIÓN, MODIFICACIÓN Y BORRADO DE            DATOS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-final-proyecto-final-confident-students/files/15473620/REALIZAR.UN.APP.QUE.CONTENGA.OPERACIONES.DE.INSERCION.MODIFICACION.Y.BORRADO.DE.DATOS.pdf)

**Comment by josealfredo79** [comment]
Bien hecho
